version: '3.6'

services:
  redis:
    image: redislabs/redis
    ports:
      - '6379:6379'

  web:
    build:
      context: ./web/
    ports:
      - "5000:5000"
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web
