services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    configs:
      - source: grafana
        target: /etc/grafana/provisioning/datasources/datasource.yml
configs:
  prometheus:
    file: ./prometheus/prometheus.yml
  grafana:
    file: ./grafana/datasource.yml
volumes:
  prom_data:
